blank_issues_enabled: false
contact_links:
  - name: Simple Gantt Discussion
    url: https://github.com/cousin-bubbles/gantt/discussions
    about: Ask questions or discuss features in GitHub Discussions